[package]
name = "orcs-app"
description = "ORCS Application Layer - Re-exports and AppError"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
orcs-types = { workspace = true }
orcs-event = { workspace = true }
orcs-component = { workspace = true }
orcs-runtime = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
